// Generated by CoffeeScript 1.3.1
var PlayerList,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

PlayerList = (function() {

  PlayerList.name = 'PlayerList';

  function PlayerList(thisPlayer, server, map, globalSpeed) {
    this.thisPlayer = thisPlayer;
    this.server = server;
    this.map = map;
    this.globalSpeed = globalSpeed;
    this.otherPlayers = __bind(this.otherPlayers, this);

    this.you = __bind(this.you, this);

    this.removePlayer = __bind(this.removePlayer, this);

    this.updatePlayer = __bind(this.updatePlayer, this);

    this.id = Math.floor(Math.random() * 10000000);
    this.players = {};
    this.players[this.id] = this.thisPlayer;
  }

  PlayerList.prototype.updatePlayer = function(id, event) {
    var player;
    if (this.players[id] != null) {
      return this.players[id].addEvent(event);
    } else {
      player = new Player(this.map, 48, this.globalSpeed);
      player.addEvent(event);
      return this.players[id] = player;
    }
  };

  PlayerList.prototype.removePlayer = function(data) {};

  PlayerList.prototype.you = function() {
    return this.thisPlayer;
  };

  PlayerList.prototype.otherPlayers = function() {
    var id, list, player, _ref;
    list = [];
    _ref = this.players;
    for (id in _ref) {
      player = _ref[id];
      if (this.thisPlayer !== player) {
        list.push(player);
      }
    }
    return list;
  };

  return PlayerList;

})();
