class Map 
    
    constructor: (@server, @sceneryTable) ->
        @lastPartLoaded = -1;
        @objects = 
            obstacles: [],
            speedup: [],
            slowdown: []

        @map = [
            "oooooooooooo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oooooooooooo                                    ",
            "                                                ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "xxxxxxxxxx                                      ",
            "xoooooooox                                      ",
            "xoooooooox                                      ",
            "xxxxxxxxxx               -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "                                                ",
            "oooooooooooo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oooooooooooo                                    ",
            "                                                ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "xxxxxxxxxx                                      ",
            "xoooooooox                                      ",
            "xoooooooox                                      ",
            "xxxxxxxxxx               -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "                                                ",
            "oooooooooooo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oooooooooooo                                    ",
            "                                                ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "xxxxxxxxxx                                      ",
            "xoooooooox                                      ",
            "xoooooooox                                      ",
            "xxxxxxxxxx               -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "                                                ",
            "oooooooooooo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oooooooooooo                                    ",
            "                                                ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "xxxxxxxxxx                                      ",
            "xoooooooox                                      ",
            "xoooooooox                                      ",
            "xxxxxxxxxx               -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "                                                ",
            "oooooooooooo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oooooooooooo                                    ",
            "                                                ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "xxxxxxxxxx                                      ",
            "xoooooooox                                      ",
            "xoooooooox                                      ",
            "xxxxxxxxxx               -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "                                                ",
            "oooooooooooo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oxxxxxxxxxxo                                    ",
            "oooooooooooo                                    ",
            "                                                ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                       +++++++++++++            ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "xxxxxxxxxx                                      ",
            "xoooooooox                                      ",
            "xoooooooox                                      ",
            "xxxxxxxxxx               -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                         -------------          ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "                                                ",
            "              ooooooooooooo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "              oxxxxxxxxxxxo                     ",
            "               oxxxxxxxxxo                      ",
            "                oxxxxxxxo                       ",
            "                 ooooooo                        ",
            "                                                ",
            "                                                ",
            "                                                ",
        ]
        
        ###
        @server.onMapSegment (data) =>
            console.log 'map data', data
            
            # add it to the array
            for e in data.obstacles
                do (e) =>
                    @objects.obstacles.push e
            #@objects.speedup.concat   newObjects.speedup
            #@objects.slowdown.concat  newObjects.slowdown

        ###

    drawArea: (offset) =>
        width = 48
        height = 57

        for y in [0..height]
            for x in [0..width]
                pixel = @getPixel(x, y + offset);
                switch pixel
                    when " " then color = [0, 0, 0, 0]
                    when "x" then color = [0, 255, 126, 1]
                    when "o" then color = [0, 0, 0, 1]
                    when "+" then color = [255, 0, 255, 1]
                    when "-" then color = [0, 255, 255, 1]
                
                @sceneryTable.setPixel x, height-y-1, color
    
    getPixel: (x,y) =>
        return @map[y].charAt(x);


    loadPart: (part) =>
        # make sure it's not already loaded
        start = @lastPartLoaded+1
        for i in [start...part]   
            @server.askForMapSegment i

        @lastPartLoaded = part
