// Generated by CoffeeScript 1.3.1
var Server,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Server = (function() {

  Server.name = 'Server';

  function Server() {
    this.playerEventCallback = __bind(this.playerEventCallback, this);

    this.sendPlayerDead = __bind(this.sendPlayerDead, this);

    this.onRemovePlayerBroadcastCallback = __bind(this.onRemovePlayerBroadcastCallback, this);

    this.onPlayerEventBroadcastCallback = __bind(this.onPlayerEventBroadcastCallback, this);

    this.onStartCallback = __bind(this.onStartCallback, this);

    this.onMapSegment = __bind(this.onMapSegment, this);

    var _this = this;
    this.socket = io.connect('http://80.81.254.39:8081');
    this.socket.on('startGame', function(data) {
      if (_this.startCallback) {
        return _this.startCallback(data.gametime, data.y);
      } else {
        return console.log('Y U NO USE Server.onStartCallback??');
      }
    });
    this.socket.on('mapSegment', function(data) {
      if (_this.callbackOnMapSegment) {
        return _this.callbackOnMapSegment(data);
      } else {
        return console.log('Y U NO USE Server.onMapSegment??');
      }
    });
    this.socket.on('playerEventBroadcast', function(data) {
      if (_this.playerEventBroadcastCallback) {
        return _this.playerEventBroadcastCallback(data.id, data.event);
      } else {
        return console.log('Y U NO USE Server.onPlayerEventBroadcastCallback??');
      }
    });
    this.socket.on('removePlayerBroadcast', function(id) {
      console.log('mashmashmahs');
      if (_this.removePlayerBroadcastCallback) {
        return _this.removePlayerBroadcastCallback(id);
      } else {
        return console.log('Y U NO USE Server.onRemovePlayerBroadcastCallback??');
      }
    });
  }

  Server.prototype.onMapSegment = function(callbackOnMapSegment) {
    this.callbackOnMapSegment = callbackOnMapSegment;
  };

  Server.prototype.onStartCallback = function(startCallback) {
    this.startCallback = startCallback;
  };

  Server.prototype.onPlayerEventBroadcastCallback = function(playerEventBroadcastCallback) {
    this.playerEventBroadcastCallback = playerEventBroadcastCallback;
  };

  Server.prototype.onRemovePlayerBroadcastCallback = function(removePlayerBroadcastCallback) {
    this.removePlayerBroadcastCallback = removePlayerBroadcastCallback;
  };

  Server.prototype.sendPlayerDead = function(id) {
    return this.socket.emit('playerDead', {
      id: id
    });
  };

  Server.prototype.playerEventCallback = function(id, event) {
    return this.socket.emit('playerEvent', {
      id: id,
      event: event
    });
  };

  return Server;

})();
