// Generated by CoffeeScript 1.3.1
var Server,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Server = (function() {

  Server.name = 'Server';

  function Server() {
    this.onGametime = __bind(this.onGametime, this);

    var _this = this;
    this.socket = io.connect('http://ec2-46-137-147-99.eu-west-1.compute.amazonaws.com:8081');
    this.socket.on('gametime', function(data) {
      if (_this.onGametime) {
        return _this.onGametime(data.gametime);
      } else {
        return console.log('Y U NO USE Server.onGametime??');
      }
    });
  }

  Server.prototype.onGametime = function(onGametime) {
    return this.onGametime = onGametime;
  };

  return Server;

})();
